# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEpSmKdgQ79dQa3lCHfXaM_S0DIp1xEw
"""

# ============================
# ransomware 실시간 탐지 모델 학습 코드
# ============================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)
from xgboost import XGBClassifier

# ----------------------------
# 1) 데이터 로드
# ----------------------------
# 네가 저장한 synthetic_realtime_dataset.csv 경로에 맞춰 수정
DATA_PATH = "/content/synthetic_ransomware_dataset_30000.csv"

df = pd.read_csv(DATA_PATH)

# 피처 / 라벨 분리
FEATURE_COLS = [
    "file_read_count",
    "file_write_count",
    "file_delete_count",
    "file_rename_count",
    "file_encrypt_like_count",
    "changed_files_count",
    "random_extension_flag",
    "entropy_diff_mean",
    "file_size_diff_mean",
]

X = df[FEATURE_COLS].copy()
y = df["label"].copy()

# 라벨을 0/1로 인코딩 (benign=0, ransomware=1)
y = (y == "ransomware").astype(int)

print("데이터 개수:", len(df))
print("라벨 분포:\n", y.value_counts())

# ----------------------------
# 2) Train / Test Split
# ----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("\nTrain size:", X_train.shape, " Test size:", X_test.shape)

# ----------------------------
# 3) XGBoost 모델 정의
#    - 꽤 무난하게 성능 잘 나오는 세팅으로 맞춰둠
# ----------------------------
model = XGBClassifier(
    n_estimators=400,         # 트리 개수
    learning_rate=0.05,      # 학습률
    max_depth=4,             # 트리 깊이 (너무 깊으면 과적합)
    subsample=0.8,           # row 샘플링 비율
    colsample_bytree=0.8,    # column 샘플링 비율
    min_child_weight=1,
    gamma=0.1,
    reg_lambda=1.0,          # L2 정규화
    objective="binary:logistic",
    eval_metric="logloss",
    n_jobs=-1,
    random_state=42,
    tree_method="hist"       # 속도용 (GPU 있으면 'gpu_hist' 가능)
)

# ----------------------------
# 4) 학습
# ----------------------------
model.fit(X_train, y_train)

# ----------------------------
# 5) 평가
# ----------------------------
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred, target_names=["benign", "ransomware"]))

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, y_pred))

roc_auc = roc_auc_score(y_test, y_proba)
pr_auc = average_precision_score(y_test, y_proba)  # AUPRC

print(f"\nROC-AUC  : {roc_auc:.4f}")
print(f"PR-AUC   : {pr_auc:.4f}")

# ----------------------------
# 6) 피처 중요도 확인 (어떤 피처가 중요한지)
# ----------------------------
importances = model.feature_importances_
feat_importance = sorted(zip(FEATURE_COLS, importances), key=lambda x: x[1], reverse=True)

print("\n=== Feature Importances (높을수록 중요) ===")
for name, score in feat_importance:
    print(f"{name:25s} : {score:.4f}")